# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-02 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import drugbank.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedOrganism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pumbedId', models.TextField()),
                ('citation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AtcCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('organism', models.TextField()),
                ('action', drugbank.models.ListField()),
                ('knownAction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('meshId', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('directParent', models.TextField()),
                ('kingdom', models.TextField()),
                ('superclass', models.TextField()),
                ('kls', models.TextField()),
                ('subclass', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.TextField()),
                ('route', models.TextField()),
                ('strength', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugbankId', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('casNumber', models.TextField()),
                ('unii', models.TextField()),
                ('state', models.TextField()),
                ('groups', drugbank.models.ListField()),
                ('synthesisReference', models.TextField()),
                ('indication', models.TextField()),
                ('pharmacodynamics', models.TextField()),
                ('mechanismOfAction', models.TextField()),
                ('toxicity', models.TextField()),
                ('selfmetabolism', models.TextField()),
                ('absorption', models.TextField()),
                ('halfLife', models.TextField()),
                ('proteinBinding', models.TextField()),
                ('routeOfElimination', models.TextField()),
                ('volumeOfDistribution', models.TextField()),
                ('clearance', models.TextField()),
                ('ahfsCodes', models.TextField()),
                ('pdbEntries', models.TextField()),
                ('fdaLabel', models.TextField()),
                ('msds', models.TextField()),
                ('foodInterations', drugbank.models.ListField()),
                ('sequences', drugbank.models.ListField()),
                ('enzymes', drugbank.models.ListField()),
            ],
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugbankId', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_drugInteractions', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinName', models.TextField()),
                ('geneSymbol', models.TextField()),
                ('uniprotId', models.TextField()),
                ('rsId', models.TextField()),
                ('allele', models.TextField()),
                ('definingChange', models.TextField()),
                ('description', models.TextField()),
                ('pubmedId', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugbankId', models.TextField()),
                ('name', models.TextField()),
                ('type', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.TextField()),
                ('identifier', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_externalIdentifiers', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.TextField()),
                ('url', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_externalLinks', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='GoClassifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('content', models.TextField()),
                ('atcCode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atcCode_levels', to='drugbank.AtcCode')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('generic', models.TextField()),
                ('url', models.TextField()),
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_manufacturers', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Mixture',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('ingredients', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_mixtures', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Packager',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_packagers', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField()),
                ('country', models.TextField()),
                ('approved', models.TextField()),
                ('expires', models.TextField()),
                ('pediatricExtension', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_patents', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smpdbId', models.TextField()),
                ('name', models.TextField()),
                ('category', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_pathways', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Polypeptide',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('source', models.TextField()),
                ('name', models.TextField()),
                ('generalFunction', models.TextField()),
                ('specificFunction', models.TextField()),
                ('geneName', models.TextField()),
                ('locus', models.TextField()),
                ('cellularLocation', models.TextField()),
                ('transmembraneRegions', models.TextField()),
                ('signalRegions', models.TextField()),
                ('theoreticalPi', models.TextField()),
                ('molecularWeight', models.TextField()),
                ('chromosomeLocation', models.TextField()),
                ('organism', models.TextField()),
                ('organismNcbiTaxonomyId', models.TextField()),
                ('aminoAcidSequence', models.TextField()),
                ('geneSequence', models.TextField()),
                ('externalIdentifiers', models.TextField()),
                ('synonyms', drugbank.models.ListField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cost', models.TextField()),
                ('unit', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_prices', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('labeller', models.TextField()),
                ('ndcId', models.TextField()),
                ('ndcProductCode', models.TextField()),
                ('dpdId', models.TextField()),
                ('emaProductCode', models.TextField()),
                ('emaMaNumber', models.TextField()),
                ('startedMarketingOn', models.TextField()),
                ('endedMarketingOn', models.TextField()),
                ('dosageForm', models.TextField()),
                ('strength', models.TextField()),
                ('route', models.TextField()),
                ('fdaApplicationNumber', models.TextField()),
                ('generic', models.TextField()),
                ('overTheCounter', models.TextField()),
                ('approved', models.TextField()),
                ('country', models.TextField()),
                ('source', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_products', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField()),
                ('value', models.TextField()),
                ('source', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_properties', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('organism', models.TextField()),
                ('action', drugbank.models.ListField()),
                ('knownAction', models.TextField()),
                ('polypeptide', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='drugbank.Polypeptide')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqence', models.IntegerField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drugs_reactions', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Salt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugbankId', drugbank.models.ListField()),
                ('name', models.TextField()),
                ('unii', models.TextField()),
                ('casNumber', models.TextField()),
                ('inchikey', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_salt', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='SnpAdverseDrugReactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinName', models.TextField()),
                ('geneSymbol', models.TextField()),
                ('uniprotId', models.TextField()),
                ('rsId', models.TextField()),
                ('allele', models.TextField()),
                ('definingChange', models.TextField()),
                ('description', models.TextField()),
                ('pubmedId', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_snpAdverseDrugReactions', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='SnpEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinName', models.TextField()),
                ('geneSymbol', models.TextField()),
                ('uniprotId', models.TextField()),
                ('rsId', models.TextField()),
                ('allele', models.TextField()),
                ('definingChange', models.TextField()),
                ('description', models.TextField()),
                ('pubmedId', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_snpEffects', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField()),
                ('coder', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_synonym', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('organism', models.TextField()),
                ('action', drugbank.models.ListField()),
                ('knownAction', models.TextField()),
                ('drug', models.ManyToManyField(related_name='drug_targets', to='drugbank.Drug')),
                ('polypeptide', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='drugbank.Polypeptide')),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_textbook', to='drugbank.Drug')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='protein_textbook', to='drugbank.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('organism', models.TextField()),
                ('action', drugbank.models.ListField()),
                ('knownAction', models.TextField()),
                ('drug', models.ManyToManyField(related_name='drug_transporters', to='drugbank.Drug')),
                ('polypeptide', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='drugbank.Polypeptide')),
            ],
        ),
        migrations.AddField(
            model_name='pfam',
            name='polypeptide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='polypeptide_pfams', to='drugbank.Polypeptide'),
        ),
        migrations.AddField(
            model_name='goclassifier',
            name='polypeptide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='polypeptide_goClassifiers', to='drugbank.Polypeptide'),
        ),
        migrations.AddField(
            model_name='element',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relation_elements', to='drugbank.Reaction'),
        ),
        migrations.AddField(
            model_name='dosage',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_dosages', to='drugbank.Drug'),
        ),
        migrations.AddField(
            model_name='classification',
            name='drug',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='drugbank.Drug'),
        ),
        migrations.AddField(
            model_name='category',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_categories', to='drugbank.Drug'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='drug',
            field=models.ManyToManyField(related_name='drug_carriers', to='drugbank.Drug'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='polypeptide',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='drugbank.Polypeptide'),
        ),
        migrations.AddField(
            model_name='atccode',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_atcCodes', to='drugbank.Drug'),
        ),
        migrations.AddField(
            model_name='article',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_article', to='drugbank.Drug'),
        ),
        migrations.AddField(
            model_name='article',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='protein_article', to='drugbank.Protein'),
        ),
        migrations.AddField(
            model_name='affectedorganism',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_affectedOrganisms', to='drugbank.Drug'),
        ),
    ]
